"""Scope the progress report key by section, because a line number is not unique.

`progress_snapshots` was keyed on `(organization_id, report_ref, line_label)` and
every test of it passed, because every test of it was synthetic and every synthetic
table had **one section holding all its rows**.

The real file does not. `TĐ BOH.xlsx :: TĐ .BOH`, read end to end:

    34 activities
    12 distinct line_label          <- activities are numbered 1, 2, 3 ... per section
    34 distinct (section_label, line_label)
     0 duplicate (section_label, line_label)

Seven system headings, each numbering its own activities from 1. So `1` under
`Zone A` and `1` under `Hệ thống cấp thoát nước` are different activities that the
old key could not tell apart, and writing a real report raised:

    UniqueViolationError: duplicate key value violates unique constraint
    "uq_progress_snapshots_org_report_line"

The section is part of the row's identity, not decoration on it. The corpus's own
`I. Hệ thống cấp nước` / `1. Bể nước sinh hoạt` hierarchy says so; the first
version of the key just did not.

A btree index on a `text` column is legal, and the longest measured section label is
87 characters — well inside the ~2704-byte tuple limit. A future sheet with a longer
heading would fail loudly on the insert rather than truncate.

## Why this is its own migration and not an edit to `0014`

`0014` has been applied to two databases. Editing an applied migration is the wrong
move even when the edit is obviously correct, because every environment that already
ran it would then disagree with the file. The index is dropped and recreated, which
is also the only safe way to change a unique constraint over existing rows — and it
is safe here because the dev and test schemas hold no progress rows yet, so nothing
collides on the wider key.

The lesson, recorded in `docs/FAILED_APPROACHES.md` F101: a constraint designed from
a fixture is a constraint designed from the fixture. The roll-up rows (F96) and this
were the same shape — both wrong about the real file's three-level hierarchy, both
invisible to synthetic tests, both found by reading `TĐ BOH.xlsx` rather than by
reasoning about the domain.

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-27 11:20:07.578642
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = '0015'
down_revision: str | None = '0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_progress_snapshots_org_report_line'), table_name='progress_snapshots')
    op.create_index('uq_progress_snapshots_org_report_line', 'progress_snapshots', ['organization_id', 'report_ref', 'section_label', 'line_label'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_progress_snapshots_org_report_line', table_name='progress_snapshots')
    op.create_index(op.f('uq_progress_snapshots_org_report_line'), 'progress_snapshots', ['organization_id', 'report_ref', 'line_label'], unique=True)
    # ### end Alembic commands ###
