"""initial schema: 44 tenant-scoped tables

Revision ID: e16621b0d3d9
Revises: 
Create Date: 2026-09-25 19:56:34.413425
"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e16621b0d3d9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `audit_log_seq` first, and it has to be here.
    #
    # `audit_logs.sequence` is declared below with
    # `server_default=nextval('audit_log_seq')`, and until this line existed no
    # migration created that sequence. The chain therefore could not build a
    # database from nothing: `make setup` worked only because the sequence had
    # been created by hand in a database that predated the migration files, and
    # every developer inherited that database. Dropping the schema and running
    # `alembic upgrade head` on an empty one failed with
    # `UndefinedTableError: relation "audit_log_seq" does not exist`.
    #
    # `IF NOT EXISTS` rather than a plain `CREATE` because this migration is the
    # initial one and the databases that already ran it *do* have the sequence.
    # Idempotent means the line is correct for a fresh build and a no-op for an
    # existing one, which is the only version of this edit that is safe to make to
    # a migration that has already been applied everywhere.
    op.execute("CREATE SEQUENCE IF NOT EXISTS audit_log_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_offsets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('consumer_name', sa.String(length=128), nullable=False),
    sa.Column('stream_name', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_event_id', sa.String(length=40), nullable=True),
    sa.Column('processed_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('duplicate_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumer_offsets')),
    sa.UniqueConstraint('consumer_name', name='uq_consumer_offsets_consumer')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=128), server_default='active', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('spend_cap_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), server_default='365', nullable=False),
    sa.Column('default_model_profile', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('default_timezone', sa.String(length=128), server_default='UTC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('spend_cap_usd IS NULL OR spend_cap_usd >= 0', name=op.f('ck_organizations_spend_cap_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('budgets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=128), nullable=False),
    sa.Column('scope_id', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=128), server_default='monthly', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('spent_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('spent_cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('period_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_tokens >= 0 AND max_cost_usd >= 0', name=op.f('ck_budgets_budget_non_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_budgets_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('organization_id', 'scope_type', 'scope_id', 'period', name='uq_budgets_scope_period')
    )
    op.create_table('connectors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('connector_type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=128), server_default='inactive', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('secret_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('requires_approval_to_activate', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_connectors_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_connectors_org_name')
    )
    op.create_table('credentials_metadata',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('secret_ref', sa.String(length=128), nullable=False),
    sa.Column('classification', sa.String(length=128), server_default='secret', nullable=False),
    sa.Column('is_configured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_credentials_metadata_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials_metadata')),
    sa.UniqueConstraint('name', name='uq_credentials_metadata_name')
    )
    op.create_table('evaluation_cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('suite_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('task_spec', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('agent_spec', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('expected_behavior', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluation_cases_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_cases'))
    )
    op.create_index('ix_eval_cases_suite', 'evaluation_cases', ['suite_name', 'is_active'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('source', sa.String(length=128), server_default='control-plane', nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('spec_version', sa.String(length=128), server_default='1.0', nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_org_subject', 'events', ['organization_id', 'subject', 'occurred_at'], unique=False)
    op.create_index('ix_events_org_type', 'events', ['organization_id', 'type', 'occurred_at'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_idempotency_records_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('idempotency_key', 'operation', name='uq_idempotency_key_operation')
    )
    op.create_index('ix_idempotency_expiry', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=128), server_default='stdio', nullable=False),
    sa.Column('endpoint', sa.String(length=128), server_default='', nullable=False),
    sa.Column('command', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('auth_secret_env', sa.String(length=128), nullable=True),
    sa.Column('auth_scheme', sa.String(length=128), server_default='none', nullable=False),
    sa.Column('is_allowlisted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tool_allowlist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('require_tls', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_payload_bytes', sa.Integer(), server_default='1048576', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_mcp_servers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers'))
    )
    op.create_table('model_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('providers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('privacy_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fallback_profile_id', sa.String(length=40), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), server_default='60000', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='2', nullable=False),
    sa.Column('requires_tool_calling', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('requires_structured_output', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fallback_profile_id'], ['model_profiles.id'], name=op.f('fk_model_profiles_fallback_profile_id_model_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_model_profiles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_profiles'))
    )
    op.create_index('ix_model_profiles_org_name', 'model_profiles', ['organization_id', 'name'], unique=False)
    op.create_table('organizational_units',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('unit_type', sa.String(length=128), server_default='department', nullable=False),
    sa.Column('purpose', sa.Text(), server_default='', nullable=False),
    sa.Column('head_agent_id', sa.String(length=40), nullable=True),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('path', sa.String(length=128), server_default='/', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> parent_id', name=op.f('ck_organizational_units_not_own_parent')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organizational_units_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['organizational_units.id'], name=op.f('fk_organizational_units_parent_id_organizational_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizational_units')),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_org_units_org_slug')
    )
    op.create_index('ix_org_units_org_parent', 'organizational_units', ['organization_id', 'parent_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('nats_subject', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_outbox_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('event_id', name='uq_outbox_events_event')
    )
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['published_at', 'created_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('scope', sa.String(length=128), server_default='organization', nullable=False),
    sa.Column('current_version_id', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_policies_org_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('parent_role_id', sa.String(length=40), nullable=True),
    sa.Column('authority_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('allowed_capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('max_autonomy', sa.String(length=128), server_default='l2_parent_review', nullable=False),
    sa.Column('may_delegate_to_peers', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('may_spawn_subagents', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_delegation_depth', sa.Integer(), server_default='2', nullable=False),
    sa.Column('is_system_role', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], name=op.f('fk_roles_parent_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_roles_org_name')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('governance_state', sa.String(length=128), server_default='experimental', nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_global', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_version_id', sa.String(length=40), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('license_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_skills_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index('ix_skills_governance', 'skills', ['governance_state'], unique=False)
    op.create_index('ix_skills_org_name', 'skills', ['organization_id', 'name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), server_default='member', nullable=False),
    sa.Column('is_org_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_privileged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index('ix_users_org_role', 'users', ['organization_id', 'role'], unique=False)
    op.create_table('agent_definitions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('system_instructions', sa.Text(), server_default='', nullable=False),
    sa.Column('behavior_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model_profile', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('allowed_child_roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('allowed_task_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('memory_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('escalation_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('prompt_version', sa.String(length=128), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_definitions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_agent_definitions_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_definitions')),
    sa.UniqueConstraint('organization_id', 'name', 'version', name='uq_agent_defs_name_version')
    )
    op.create_index('ix_agent_defs_org_role', 'agent_definitions', ['organization_id', 'role_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('org_unit_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), server_default='text/plain', nullable=False),
    sa.Column('storage_uri', sa.String(length=128), server_default='', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('classification', sa.String(length=128), server_default='internal', nullable=False),
    sa.Column('source_type', sa.String(length=128), server_default='upload', nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organizational_units.id'], name=op.f('fk_documents_org_unit_id_organizational_units')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('organization_id', 'content_hash', name='uq_documents_org_hash')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_policy_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_versions_policy_id_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions'))
    )
    op.create_index('uq_policy_versions_current', 'policy_versions', ['organization_id', 'policy_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('skill_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('skill_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('instructions', sa.Text(), server_default='', nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('required_tool_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('required_permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('required_data_scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_requirements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('budget_constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('risk_level', sa.String(length=128), server_default='low', nullable=False),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('security_scan', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_skill_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_versions_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_versions')),
    sa.UniqueConstraint('organization_id', 'skill_id', 'version', name='uq_skill_versions_skill_version')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('risk_level', sa.String(length=128), server_default='low_risk_write', nullable=False),
    sa.Column('effect_class', sa.String(length=128), server_default='mutate_internal', nullable=False),
    sa.Column('required_scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('data_classification', sa.String(length=128), server_default='internal', nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), server_default='60', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_mcp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mcp_server_id', sa.String(length=40), nullable=True),
    sa.Column('current_version_id', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], name=op.f('fk_tools_mcp_server_id_mcp_servers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tools_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    op.create_index('ix_tools_org_name', 'tools', ['organization_id', 'name'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('org_unit_id', sa.String(length=40), nullable=True),
    sa.Column('definition_id', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('parent_agent_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('lifecycle_status', sa.String(length=128), server_default='draft', nullable=False),
    sa.Column('runtime_status', sa.String(length=128), server_default='idle', nullable=False),
    sa.Column('health', sa.String(length=128), server_default='unknown', nullable=False),
    sa.Column('autonomy_level', sa.String(length=128), server_default='l2_parent_review', nullable=False),
    sa.Column('runtime_adapter', sa.String(length=128), server_default='pydantic_ai', nullable=False),
    sa.Column('model_profile', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('budget_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('active_tasks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('queue_depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('definition_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('budget_limit_usd IS NULL OR budget_limit_usd >= 0', name=op.f('ck_agents_budget_non_negative')),
    sa.ForeignKeyConstraint(['definition_id'], ['agent_definitions.id'], name=op.f('fk_agents_definition_id_agent_definitions')),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organizational_units.id'], name=op.f('fk_agents_org_unit_id_organizational_units')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agents_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agents.id'], name=op.f('fk_agents_parent_agent_id_agents')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_agents_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_agents_org_name')
    )
    op.create_index('ix_agents_capabilities_gin', 'agents', ['capabilities'], unique=False, postgresql_using='gin')
    op.create_index('ix_agents_discovery', 'agents', ['organization_id', 'lifecycle_status', 'runtime_status'], unique=False)
    op.create_index('ix_agents_org_parent', 'agents', ['organization_id', 'parent_agent_id'], unique=False)
    op.create_index('ix_agents_org_status', 'agents', ['organization_id', 'lifecycle_status'], unique=False)
    op.create_index('ix_agents_org_unit', 'agents', ['organization_id', 'org_unit_id'], unique=False)
    op.create_table('tool_policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('tool_id', sa.String(length=40), nullable=False),
    sa.Column('max_calls_per_task', sa.Integer(), server_default='50', nullable=False),
    sa.Column('max_cost_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('require_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('require_audit', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allowed_agents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('denied_agents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tool_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_policies_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_policies')),
    sa.UniqueConstraint('organization_id', 'tool_id', name='uq_tool_policies_org_tool')
    )
    op.create_table('tool_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('tool_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('implementation_ref', sa.String(length=128), server_default='', nullable=False),
    sa.Column('is_idempotent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('log_payload', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tool_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_versions_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_versions')),
    sa.UniqueConstraint('organization_id', 'tool_id', 'version', name='uq_tool_versions_tool_version')
    )
    op.create_table('a2a_agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('local_agent_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('supported_tasks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('protocol_version', sa.String(length=128), server_default='0.3.0', nullable=False),
    sa.Column('agent_card', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('card_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('card_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_scheme', sa.String(length=128), server_default='none', nullable=False),
    sa.Column('auth_secret_ref', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('health', sa.String(length=128), server_default='unknown', nullable=False),
    sa.Column('availability', sa.String(length=128), server_default='unknown', nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['local_agent_id'], ['agents.id'], name=op.f('fk_a2a_agents_local_agent_id_agents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_a2a_agents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_a2a_agents'))
    )
    op.create_index('ix_a2a_agents_org', 'a2a_agents', ['organization_id', 'is_active'], unique=False)
    op.create_table('agent_relationships',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('source_agent_id', sa.String(length=40), nullable=False),
    sa.Column('target_agent_id', sa.String(length=40), nullable=False),
    sa.Column('relationship_type', sa.String(length=128), server_default='peer', nullable=False),
    sa.Column('can_delegate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_risk', sa.String(length=128), server_default='low', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_agent_id <> target_agent_id', name=op.f('ck_agent_relationships_no_self_edge')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_relationships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], name=op.f('fk_agent_relationships_source_agent_id_agents')),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], name=op.f('fk_agent_relationships_target_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_relationships')),
    sa.UniqueConstraint('organization_id', 'source_agent_id', 'target_agent_id', 'relationship_type', name='uq_agent_rel_edge')
    )
    op.create_table('agent_skill_bindings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('skill_id', sa.String(length=40), nullable=False),
    sa.Column('skill_version_id', sa.String(length=40), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('granted_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_skill_bindings_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_skill_bindings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_agent_skill_bindings_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], name=op.f('fk_agent_skill_bindings_skill_version_id_skill_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_skill_bindings')),
    sa.UniqueConstraint('agent_id', 'skill_id', name='uq_agent_skill_bindings')
    )
    op.create_table('agent_tool_bindings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('tool_id', sa.String(length=40), nullable=False),
    sa.Column('max_risk', sa.String(length=128), server_default='medium', nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('rate_limit_override', sa.Integer(), nullable=True),
    sa.Column('granted_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_tool_bindings_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_tool_bindings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_agent_tool_bindings_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tool_bindings')),
    sa.UniqueConstraint('agent_id', 'tool_id', name='uq_agent_tool_bindings')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('org_unit_id', sa.String(length=40), nullable=True),
    sa.Column('parent_task_id', sa.String(length=40), nullable=True),
    sa.Column('root_task_id', sa.String(length=40), nullable=True),
    sa.Column('requester_id', sa.String(length=40), nullable=True),
    sa.Column('requester_type', sa.String(length=128), server_default='human', nullable=False),
    sa.Column('owner_agent_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=128), server_default='execution', nullable=False),
    sa.Column('status', sa.String(length=128), server_default='created', nullable=False),
    sa.Column('priority', sa.String(length=128), server_default='normal', nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('expected_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('dedup_key', sa.String(length=96), nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('budget_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('spent_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('spent_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organizational_units.id'], name=op.f('fk_tasks_org_unit_id_organizational_units')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tasks_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agents.id'], name=op.f('fk_tasks_owner_agent_id_agents')),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('fk_tasks_parent_task_id_tasks')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_tasks_requester_id_users')),
    sa.ForeignKeyConstraint(['root_task_id'], ['tasks.id'], name=op.f('fk_tasks_root_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_fingerprint', 'tasks', ['organization_id', 'fingerprint', 'status'], unique=False)
    op.create_index('ix_tasks_org_owner', 'tasks', ['organization_id', 'owner_agent_id', 'status'], unique=False)
    op.create_index('ix_tasks_org_status', 'tasks', ['organization_id', 'status'], unique=False)
    op.create_index('ix_tasks_parent', 'tasks', ['parent_task_id'], unique=False)
    op.create_index('uq_tasks_active_dedup_key', 'tasks', ['organization_id', 'dedup_key'], unique=True, postgresql_where=sa.text("status NOT IN ('completed','failed','canceled','expired')"))
    op.create_table('a2a_endpoints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('a2a_agent_id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=128), server_default='jsonrpc', nullable=False),
    sa.Column('require_tls', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_concurrent_calls', sa.Integer(), server_default='4', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['a2a_agent_id'], ['a2a_agents.id'], name=op.f('fk_a2a_endpoints_a2a_agent_id_a2a_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_a2a_endpoints_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_a2a_endpoints')),
    sa.UniqueConstraint('a2a_agent_id', 'url', name='uq_a2a_endpoints_agent_url')
    )
    op.create_table('delegations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('parent_task_id', sa.String(length=40), nullable=False),
    sa.Column('child_task_id', sa.String(length=40), nullable=True),
    sa.Column('source_agent_id', sa.String(length=40), nullable=False),
    sa.Column('target_agent_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=128), server_default='proposed', nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('delegation_path', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('depth', sa.Integer(), server_default='1', nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('budget_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('required_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], name=op.f('fk_delegations_child_task_id_tasks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_delegations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('fk_delegations_parent_task_id_tasks')),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], name=op.f('fk_delegations_source_agent_id_agents')),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], name=op.f('fk_delegations_target_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delegations'))
    )
    op.create_index('ix_delegations_org_status', 'delegations', ['organization_id', 'status'], unique=False)
    op.create_index('ix_delegations_parent_task', 'delegations', ['parent_task_id'], unique=False)
    op.create_index('ix_delegations_source', 'delegations', ['organization_id', 'source_agent_id', 'status'], unique=False)
    op.create_index('ix_delegations_target', 'delegations', ['organization_id', 'target_agent_id', 'status'], unique=False)
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('org_unit_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('tier', sa.String(length=128), server_default='working', nullable=False),
    sa.Column('kind', sa.String(length=128), server_default='note', nullable=False),
    sa.Column('title', sa.String(length=255), server_default='', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=128), server_default='internal', nullable=False),
    sa.Column('source_type', sa.String(length=128), server_default='agent', nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_memory_items_agent_id_agents')),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organizational_units.id'], name=op.f('fk_memory_items_org_unit_id_organizational_units')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memory_items_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_memory_items_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_items'))
    )
    op.create_index('ix_memory_agent', 'memory_items', ['organization_id', 'agent_id'], unique=False)
    op.create_index('ix_memory_expiry', 'memory_items', ['retention_until'], unique=False, postgresql_where=sa.text('retention_until IS NOT NULL'))
    op.create_index('ix_memory_org_tier', 'memory_items', ['organization_id', 'tier', 'created_at'], unique=False)
    op.create_index('ix_memory_unit', 'memory_items', ['organization_id', 'org_unit_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('thread_id', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('sender_type', sa.String(length=128), nullable=False),
    sa.Column('sender_id', sa.String(length=40), nullable=True),
    sa.Column('sender_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('role', sa.String(length=128), server_default='note', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_messages_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_org_task', 'messages', ['organization_id', 'task_id', 'created_at'], unique=False)
    op.create_index('ix_messages_thread', 'messages', ['organization_id', 'thread_id', 'created_at'], unique=False)
    op.create_table('subagent_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('parent_task_id', sa.String(length=40), nullable=False),
    sa.Column('parent_agent_id', sa.String(length=40), nullable=False),
    sa.Column('child_task_id', sa.String(length=40), nullable=True),
    sa.Column('virtual_agent_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=128), server_default='spawning', nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('context_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tool_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('skill_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('spawn_depth', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_fanout', sa.Integer(), server_default='0', nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('budget_limit_tokens', sa.Integer(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), server_default='600', nullable=False),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_fanout >= 0', name=op.f('ck_subagent_runs_fanout_non_negative')),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], name=op.f('fk_subagent_runs_child_task_id_tasks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_subagent_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agents.id'], name=op.f('fk_subagent_runs_parent_agent_id_agents')),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('fk_subagent_runs_parent_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subagent_runs'))
    )
    op.create_index('ix_subagent_runs_parent', 'subagent_runs', ['organization_id', 'parent_agent_id', 'status'], unique=False)
    op.create_index('ix_subagent_runs_task', 'subagent_runs', ['parent_task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('depends_on_task_id', sa.String(length=40), nullable=False),
    sa.Column('dependency_type', sa.String(length=128), server_default='finish_to_start', nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name=op.f('ck_task_dependencies_no_self_dependency')),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_task_dependencies_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_deps_edge')
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('workflow_type', sa.String(length=128), nullable=False),
    sa.Column('workflow_version', sa.String(length=128), server_default='v1', nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=128), nullable=False),
    sa.Column('temporal_run_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=128), server_default='running', nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('current_step', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflow_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_workflow_runs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs')),
    sa.UniqueConstraint('temporal_workflow_id', name='uq_workflow_runs_temporal')
    )
    op.create_index('ix_workflow_runs_org_status', 'workflow_runs', ['organization_id', 'status'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('delegation_id', sa.String(length=40), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=128), server_default='running', nullable=False),
    sa.Column('runtime_adapter', sa.String(length=128), server_default='pydantic_ai', nullable=False),
    sa.Column('model_profile', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('agent_definition_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('skill_versions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tool_versions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('policy_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('decision_record', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('escalation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_kind', sa.String(length=128), nullable=True),
    sa.Column('error_category', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_executions_agent_id_agents')),
    sa.ForeignKeyConstraint(['delegation_id'], ['delegations.id'], name=op.f('fk_executions_delegation_id_delegations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_executions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_executions_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index('ix_executions_agent', 'executions', ['organization_id', 'agent_id', 'created_at'], unique=False)
    op.create_index('ix_executions_org_task', 'executions', ['organization_id', 'task_id'], unique=False)
    op.create_index('ix_executions_trace', 'executions', ['trace_id'], unique=False)
    op.create_table('memory_chunks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('memory_item_id', sa.String(length=40), nullable=False),
    sa.Column('chunk_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_item_id'], ['memory_items.id'], name=op.f('fk_memory_chunks_memory_item_id_memory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memory_chunks_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_chunks')),
    sa.UniqueConstraint('memory_item_id', 'chunk_index', name='uq_memory_chunks_item_index')
    )
    op.create_index('ix_memory_chunks_org_model', 'memory_chunks', ['organization_id', 'embedding_model'], unique=False)
    op.create_index('ix_memory_chunks_vector', 'memory_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('approvals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('effect_class', sa.String(length=128), server_default='mutate_internal', nullable=False),
    sa.Column('risk_level', sa.String(length=128), server_default='medium', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=40), nullable=False),
    sa.Column('requested_by_type', sa.String(length=128), server_default='agent', nullable=False),
    sa.Column('required_approver_roles', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('assigned_approver_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=128), server_default='pending', nullable=False),
    sa.Column('decision', sa.String(length=128), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_name', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'approved' OR decided_at IS NOT NULL", name=op.f('ck_approvals_approved_requires_decision_time')),
    sa.ForeignKeyConstraint(['assigned_approver_id'], ['users.id'], name=op.f('fk_approvals_assigned_approver_id_users')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_approvals_execution_id_executions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_approvals_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_approvals_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index('ix_approvals_org_status', 'approvals', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_approvals_task', 'approvals', ['task_id'], unique=False)
    op.create_table('blackboard_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('slot', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('written_by_agent_id', sa.String(length=40), nullable=True),
    sa.Column('written_by_execution_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_blackboard_entries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_blackboard_entries_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['written_by_agent_id'], ['agents.id'], name=op.f('fk_blackboard_entries_written_by_agent_id_agents')),
    sa.ForeignKeyConstraint(['written_by_execution_id'], ['executions.id'], name=op.f('fk_blackboard_entries_written_by_execution_id_executions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blackboard_entries')),
    sa.UniqueConstraint('task_id', 'slot', name='uq_blackboard_task_slot')
    )
    op.create_table('budget_ledger',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('budget_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('entry_type', sa.String(length=128), nullable=False),
    sa.Column('tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('reverses_entry_id', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_budget_ledger_budget_id_budgets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_budget_ledger_execution_id_executions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_budget_ledger_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['budget_ledger.id'], name=op.f('fk_budget_ledger_reverses_entry_id_budget_ledger')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_budget_ledger_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_ledger'))
    )
    op.create_index('ix_budget_ledger_budget', 'budget_ledger', ['budget_id', 'created_at'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('runtime_adapter', sa.String(length=128), nullable=False),
    sa.Column('model_profile', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('observed_behavior', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('success', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('failure_category', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], name=op.f('fk_evaluation_runs_case_id_evaluation_cases')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_evaluation_runs_execution_id_executions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluation_runs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_eval_runs_adapter', 'evaluation_runs', ['runtime_adapter', 'success'], unique=False)
    op.create_index('ix_eval_runs_case', 'evaluation_runs', ['case_id', 'runtime_adapter'], unique=False)
    op.create_table('model_usage',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('model_profile', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('routing_reason', sa.String(length=128), server_default='primary', nullable=False),
    sa.Column('status', sa.String(length=128), server_default='ok', nullable=False),
    sa.Column('error_kind', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_model_usage_agent_id_agents')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_model_usage_execution_id_executions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_model_usage_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_model_usage_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_usage'))
    )
    op.create_index('ix_model_usage_agent', 'model_usage', ['organization_id', 'agent_id'], unique=False)
    op.create_index('ix_model_usage_org_time', 'model_usage', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_model_usage_task', 'model_usage', ['task_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('sequence', sa.BigInteger(), server_default=sa.text("nextval('audit_log_seq')"), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_type', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=128), server_default='success', nullable=False),
    sa.Column('policy_decision', sa.String(length=128), nullable=True),
    sa.Column('policy_rule_id', sa.String(length=128), nullable=True),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_audit_logs_approval_id_approvals')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_audit_logs_execution_id_executions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_audit_logs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['organization_id', 'actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_sequence'), 'audit_logs', ['sequence'], unique=True)
    op.create_index('ix_audit_org_time', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_task', 'audit_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_task', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_org_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sequence'), table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_model_usage_task', table_name='model_usage')
    op.drop_index('ix_model_usage_org_time', table_name='model_usage')
    op.drop_index('ix_model_usage_agent', table_name='model_usage')
    op.drop_table('model_usage')
    op.drop_index('ix_eval_runs_case', table_name='evaluation_runs')
    op.drop_index('ix_eval_runs_adapter', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_budget_ledger_budget', table_name='budget_ledger')
    op.drop_table('budget_ledger')
    op.drop_table('blackboard_entries')
    op.drop_index('ix_approvals_task', table_name='approvals')
    op.drop_index('ix_approvals_org_status', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_memory_chunks_vector', table_name='memory_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_memory_chunks_org_model', table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index('ix_executions_trace', table_name='executions')
    op.drop_index('ix_executions_org_task', table_name='executions')
    op.drop_index('ix_executions_agent', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_workflow_runs_org_status', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('task_dependencies')
    op.drop_index('ix_subagent_runs_task', table_name='subagent_runs')
    op.drop_index('ix_subagent_runs_parent', table_name='subagent_runs')
    op.drop_table('subagent_runs')
    op.drop_index('ix_messages_thread', table_name='messages')
    op.drop_index('ix_messages_org_task', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_memory_unit', table_name='memory_items')
    op.drop_index('ix_memory_org_tier', table_name='memory_items')
    op.drop_index('ix_memory_expiry', table_name='memory_items', postgresql_where=sa.text('retention_until IS NOT NULL'))
    op.drop_index('ix_memory_agent', table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index('ix_delegations_target', table_name='delegations')
    op.drop_index('ix_delegations_source', table_name='delegations')
    op.drop_index('ix_delegations_parent_task', table_name='delegations')
    op.drop_index('ix_delegations_org_status', table_name='delegations')
    op.drop_table('delegations')
    op.drop_table('a2a_endpoints')
    op.drop_index('uq_tasks_active_dedup_key', table_name='tasks', postgresql_where=sa.text("status NOT IN ('completed','failed','canceled','expired')"))
    op.drop_index('ix_tasks_parent', table_name='tasks')
    op.drop_index('ix_tasks_org_status', table_name='tasks')
    op.drop_index('ix_tasks_org_owner', table_name='tasks')
    op.drop_index('ix_tasks_fingerprint', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('agent_tool_bindings')
    op.drop_table('agent_skill_bindings')
    op.drop_table('agent_relationships')
    op.drop_index('ix_a2a_agents_org', table_name='a2a_agents')
    op.drop_table('a2a_agents')
    op.drop_table('tool_versions')
    op.drop_table('tool_policies')
    op.drop_index('ix_agents_org_unit', table_name='agents')
    op.drop_index('ix_agents_org_status', table_name='agents')
    op.drop_index('ix_agents_org_parent', table_name='agents')
    op.drop_index('ix_agents_discovery', table_name='agents')
    op.drop_index('ix_agents_capabilities_gin', table_name='agents', postgresql_using='gin')
    op.drop_table('agents')
    op.drop_index('ix_tools_org_name', table_name='tools')
    op.drop_table('tools')
    op.drop_table('skill_versions')
    op.drop_index('uq_policy_versions_current', table_name='policy_versions', postgresql_where=sa.text('is_current'))
    op.drop_table('policy_versions')
    op.drop_table('documents')
    op.drop_index('ix_agent_defs_org_role', table_name='agent_definitions')
    op.drop_table('agent_definitions')
    op.drop_index('ix_users_org_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_skills_org_name', table_name='skills')
    op.drop_index('ix_skills_governance', table_name='skills')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_table('policies')
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_org_units_org_parent', table_name='organizational_units')
    op.drop_table('organizational_units')
    op.drop_index('ix_model_profiles_org_name', table_name='model_profiles')
    op.drop_table('model_profiles')
    op.drop_table('mcp_servers')
    op.drop_index('ix_idempotency_expiry', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_events_org_type', table_name='events')
    op.drop_index('ix_events_org_subject', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_eval_cases_suite', table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    op.drop_table('credentials_metadata')
    op.drop_table('connectors')
    op.drop_table('budgets')
    op.drop_table('organizations')
    op.drop_table('consumer_offsets')
    # ### end Alembic commands ###
