"""Finish an autogenerated Alembic revision: docstring, RLS, grants.

`alembic revision --autogenerate` emits the table bodies and nothing else. Two
things are always missing, and both have to be added by hand every time:

1. **RLS and grants.** Autogenerate has no opinion about tenancy, so a generated
   migration creates unprotected tenant tables. This was done by hand for
   migration `0007` and it is exactly the kind of step that gets forgotten on
   tranche five, on a day when someone is tired. The `_protect` call is the same
   one 0002 and 0007 use, including `FORCE` — without `FORCE` the table owner
   bypasses the policy, and the owner is the role that ran the migration.

2. **Why the migration exists.** A generated file's docstring is
   `"<message>"`. Every other migration in this repository explains the decision
   and the alternative, because that is the part a reader six months from now
   needs and the part autogenerate cannot know.

3. **A missing import.** Autogenerate emits `postgresql.JSONB(...)` for a JSONB
   column and never writes the `from sqlalchemy.dialects import postgresql` line
   that makes the name resolve. This tool adds it when the body needs it.

Usage:

    alembic -c migrations/alembic.ini revision --autogenerate \\
        -m "commercial front end" --rev-id 0008
    python scripts/finish_migration.py 0008

The tenant table list is derived from the file rather than passed in, so it
cannot disagree with what the migration actually creates. Deriving it is the
whole value: a hand-maintained list is a list that drifts, and
`tests/integration/test_construction_domain.py` asserts the two agree.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

VERSIONS = Path(__file__).resolve().parents[1] / "migrations" / "versions"

HEADER = '''"""{title}

{body}
Revision ID: {revision}
Revises: {down_revision}
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
{extra_imports}
revision: str = "{revision}"
down_revision: str | None = "{down_revision}"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Every table this migration creates, derived from the file rather than typed
#: in, so "protected" and "created" cannot drift apart. Every one of these is
#: organisation-scoped, including the ones that do not look like business tables
#: such as a controlled vocabulary: a policy on those is meaningful too.
TENANT_TABLES = (
{tables}
)

APP_ROLE = "ao_app"


def _protect(table: str) -> None:
    """Enable and force RLS, install the isolation policy, grant DML.

    Identical to what 0002 did for the original 44 tables and what 0007 did for
    the first construction tranche, including the `FORCE`. Without `FORCE` the
    owner bypasses the policy, and the owner is the role that ran this migration.
    """
    op.execute(f\'ALTER TABLE "{{table}}" ENABLE ROW LEVEL SECURITY\')
    op.execute(f\'ALTER TABLE "{{table}}" FORCE ROW LEVEL SECURITY\')
    op.execute(f\'DROP POLICY IF EXISTS tenant_isolation ON "{{table}}"\')
    op.execute(
        f\'CREATE POLICY tenant_isolation ON "{{table}}" \'
        "USING (organization_id = current_setting(\'app.current_tenant\', true)) "
        "WITH CHECK (organization_id = current_setting(\'app.current_tenant\', true))"
    )
    op.execute(f\'GRANT SELECT, INSERT, UPDATE, DELETE ON "{{table}}" TO {{APP_ROLE}}\')


def upgrade() -> None:
'''

FOOTER = """

    # RLS last, so every table exists before any policy is created.
    # `transaction_per_migration` is on in `migrations/env.py`, so this either
    # fully applies or fully rolls back; a half-protected tranche is not a
    # reachable state.
    for _table in TENANT_TABLES:
        _protect(_table)


def downgrade() -> None:
    # `DROP TABLE` takes its policies with it, so there is nothing to unprotect
    # explicitly. The drop order below is Alembic's own reverse-dependency
    # order, so children go before parents.
"""

DEFAULT_BODY = """{summary}

The table bodies are Alembic's own output, generated rather than retyped, so this
migration and the models are the same schema by construction rather than by
review. Regenerate rather than edit: this file is the models translated, and
hand-editing the two is how they stop agreeing.

Provenance (`source`, `source_actor`, `proposal_id`) and its two check constraints
come from `domain_args` in the models, not from here, so they cannot be forgotten
on a table that declares its own indexes.
"""


def finish(revision: str, body: str | None = None) -> Path:
    candidates = sorted(VERSIONS.glob(f"{revision}_*.py"))
    if len(candidates) != 1:
        raise SystemExit(f"expected exactly one file for revision {revision}, found {candidates}")
    source = candidates[0]
    lines = source.read_text().splitlines()

    try:
        start = next(i for i, line in enumerate(lines) if "op.create_table(" in line)
        end = next(i for i, line in enumerate(lines) if line.strip().startswith("def downgrade()"))
    except StopIteration:
        raise SystemExit(f"{source.name} has no create_table block; nothing to finish") from None

    create = "\n".join(lines[start:end]).rstrip()
    downgrade = "\n".join(lines[end + 1 :]).rstrip()
    for marker in (
        "    # ### commands auto generated by Alembic - please adjust! ###",
        "    # ### end Alembic commands ###",
    ):
        create = create.replace(marker, "")
        downgrade = downgrade.replace(marker, "")

    tables = re.findall(r"op\.create_table\(\s*'([a-z_]+)'", create)
    if not tables:
        raise SystemExit(f"{source.name}: could not determine the created tables")

    # Autogenerate emits `postgresql.JSONB(...)` for a JSONB column but does not
    # write the `from sqlalchemy.dialects import postgresql` line that makes the
    # name resolve. It reads as a dialect-namespaced attribute, so it looks fine
    # in a diff and the migration fails at `upgrade` with a bare
    # `NameError: name 'postgresql' is not defined` — which names neither the
    # column nor the cause.
    #
    # Found by running the migration, having grepped its own output for "ERROR"
    # and not matching, because a Python exception is not spelled in capitals.
    extra_imports = ""
    needs_postgresql = bool(re.search(r"\bpostgresql\.", create))
    already_imported = "from sqlalchemy.dialects import postgresql" in create
    if needs_postgresql and not already_imported:
        extra_imports = "from sqlalchemy.dialects import postgresql\n\n"

    down_revision = re.search(r"down_revision: str \| None = '([0-9a-z]+)'", "\n".join(lines))
    if down_revision is None:
        raise SystemExit(f"{source.name}: no down_revision")

    header = HEADER.format(
        title=f"Construction domain, tranche {revision}: "
        + ", ".join(tables[:-1])
        + (f" and {tables[-1]}" if len(tables) > 1 else ""),
        body=body or DEFAULT_BODY.format(summary=f"Tables: {', '.join(tables)}."),
        extra_imports=extra_imports,
        revision=revision,
        down_revision=down_revision.group(1),
        tables="".join(f'    "{t}",\n' for t in sorted(tables)),
    )

    target = source.with_name(f"{revision}_{'_'.join(sorted(tables)[:2])}.py")
    target.write_text(header + create + "\n" + FOOTER + downgrade + "\n")
    if target != source:
        source.unlink()
    return target


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    written = finish(argv[1])
    print(f"wrote {written.relative_to(VERSIONS.parents[1])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
