"""Put one real, model-free run on the register before the console is verified.

## Why this exists

`verify_page.mjs` checks the console **against real data**: that the stream carries events,
that the register has rows, that an office panel separates its own work from its
departments'. Every one of those is a claim about *rendered output*, so the instrument has
to render something.

On a tenant that already had history it did. Then the owner's instruction was to delete
every task generated by testing, to start their own work from an empty company — and the
harness correctly reported:

```
FAIL  the stream carries events  — 0 frames
FAIL  the event shape has `id`   — keys: none
... five more
```

**Which is the harness telling the truth and the fixture having been load-bearing.** The
checks were never wrong; they had been silently relying on a tenant someone else had
filled. A verification step that only passes when the database happens to contain the right
rows is a step that will fail on a clean machine, in CI, and for the next person.

## It costs nothing and it is deterministic

The provider is forced to `fake` (`config/settings.py`: `model_provider_default = "fake"`,
and `Environment.TEST` *requires* it). A scripted run delegates, executes and settles in
under a second and spends no tokens, so this is not a "call the model to test" compromise —
it is the same path the 3000-test suite takes, at one task instead of thousands.

## What it deliberately does not do

It does **not** clean up afterwards. A register with one honest row is more useful than an
empty one, and the owner asked for a company to work in, not a pristine fixture. It skips
when the tenant already has work, so it never becomes the source of the data it checks.
"""

from __future__ import annotations

import asyncio
import sys
import warnings

warnings.filterwarnings("ignore")
sys.path.insert(0, "src")

from sqlalchemy import text  # noqa: E402

from ai_orchestrator.application.local_runner import start  # noqa: E402
from ai_orchestrator.persistence.repositories.task import TaskRepository  # noqa: E402
from ai_orchestrator.persistence.session import Database  # noqa: E402


async def main() -> int:
    org = sys.argv[1] if len(sys.argv) > 1 else None
    if not org:
        print("  note: no organization given; skipping")
        return 0

    db = Database.from_settings(use_admin_role=True)
    try:
        async with db.session() as session:
            existing = (
                await session.execute(
                    text("SELECT count(*) FROM tasks WHERE organization_id = :o"),
                    {"o": org},
                )
            ).scalar()
        if existing:
            # **Not "return early".** The first version did, and it left two `assigned`
            # tasks with no execution -- which `abandon_unclaimed_tasks` then failed an
            # hour later as abandoned, so the console showed two failures that were really
            # this script's half-finished work.
            #
            # So: an existing register is not a reason to skip, it is a reason to **start
            # anything that is not already running**. Idempotent by state, not by count,
            # which is the only kind of idempotence that survives its own first run.
            print(f"  the register already has {existing} task(s); making sure they are run")
        else:
            print("  the register is empty; seeding two scripted runs")

        if not existing:
            async with db.committing_tenant_session(org) as session:
                chief = (
                    await session.execute(
                        # **`agents` has no `depth` column** — depth lives on
                        # `organizational_units`. Ordered through the unit so the chief is
                        # picked rather than whichever agent sorts first, which the harness
                        # would then check coordination behaviour against.
                        text(
                            "SELECT a.id FROM agents a"
                            " LEFT JOIN organizational_units u ON u.id = a.org_unit_id"
                            " WHERE a.organization_id = :o"
                            " ORDER BY COALESCE(u.depth, 99), a.name LIMIT 1"
                        ),
                        {"o": org},
                    )
                ).scalar()
                if chief is None:
                    print(f"  org {org} has no agent; run `make seed` first")
                    return 0
                repo = TaskRepository(session, org)
                task = await repo.create(
                    title="Reconcile the August ledger",
                    goal=(
                        "Reconcile the August supplier invoices against the purchase orders and "
                        "list the ones that do not match, with the difference for each."
                    ),
                    # **`analysis`, not `coordination`** — and that is the point, not a
                    # convenience. A coordination task that completes without delegating is
                    # failed by the platform on purpose (a fleet that answers everything itself
                    # is not a fleet), so a `coordination` fixture using the *scripted* runtime
                    # is guaranteed to end `failed`, and the harness would then be verifying
                    # the console against a task that broke because I chose the wrong type.
                    task_type="analysis",
                    requester_type="human",
                    owner_agent_id=str(chief),
                    allow_parallel=True,
                    # **No output contract on this one.** The scripted runtime answers with a
                    # fixed sentence and cannot produce declared keys, so a contract here
                    # would fail a task that did nothing wrong -- and the harness would then be
                    # verifying the console against a fixture I had broken myself.
                    input={"owning_office": "front-office"},
                )
                await repo.assign(task.id, str(chief))

                # **The second task fails on purpose, and nothing about it is staged.**
                #
                # A register of successes only cannot show the Issues panel, the retry path or
                # the "what went wrong" wording -- which are the parts a person opens this to
                # see. This one is a real `no_delegation` outcome: the scripted runtime cannot
                # call `delegate_to_agent`, and a coordination task that answers alone is
                # failed by the platform on purpose. The same thing happens when a model
                # ignores its instructions.
                stuck = await repo.create(
                    title="Q3 board pack",
                    goal=(
                        "Prepare the Q3 board pack: research the market with Marketing, assess "
                        "risk with Risk, and summarise the numbers with Finance."
                    ),
                    task_type="coordination",
                    requester_type="human",
                    owner_agent_id=str(chief),
                    allow_parallel=True,
                )
                await repo.assign(stuck.id, str(chief))
                await session.commit()

        # `tenant_session` owns **one** transaction and commits it on exit, so nothing
        # here may `commit()`: doing so closes the transaction and every later statement
        # raises `InvalidRequestError: can't operate on closed transaction inside context
        # manager`. That is exactly what happened here, three times, before it was read
        # off the error rather than guessed at.
        async with Database.from_settings().tenant_session(org) as session:
            pending = [
                str(t)
                for t in (
                    await session.execute(
                        text(
                            "SELECT id FROM tasks WHERE organization_id = :o"
                            " AND status IN ('created', 'assigned')"
                            # **Only tasks with an owner.** `local_runner.start` raises
                            # `ConflictError` on an ownerless task -- correctly, since
                            # there is nothing to run -- and this script is a fixture, not
                            # a validator. The harness itself creates an ownerless task to
                            # check the retry refusal, so without this filter every
                            # `make page` after the first one died on the harness's own
                            # test data.
                            " AND owner_agent_id IS NOT NULL"
                            " AND NOT (input ?| ARRAY['business_workflow',"
                            " 'agent_workflow', 'agent_blueprint_draft'])"
                        ),
                        {"o": org},
                    )
                ).scalars()
            ]
            started = 0
            for tid in pending:
                handle = await start(session, organization_id=org, task_id=tid)
                started += 1 if handle.started else 0
            print(f"  started {started} of {len(pending)} runnable task(s)")
            watched = list(pending)

        # Now the block has committed, so a fresh session per poll is safe and each poll
        # sees what the background run wrote.
        for _ in range(60):
            if not watched:
                break
            still: list[str] = []
            async with Database.from_settings().tenant_session(org) as session:
                for tid in watched:
                    row = (
                        await session.execute(
                            text("SELECT status FROM tasks WHERE organization_id = :o AND id = :t"),
                            {"o": org, "t": tid},
                        )
                    ).scalar()
                    if str(row) in ("completed", "failed", "cancelled", "blocked"):
                        print(f"  {tid} settled as {row}")
                    else:
                        still.append(tid)
            watched = still
            if watched:
                await asyncio.sleep(0.5)
        if watched:
            print(f"  still running after 30s: {len(watched)}")
        return 0
    finally:
        await db.dispose()


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
